en: wI+s1y₂kEQ!röMO0G98.&x,ú52aNeuiLdc–SBmq%"-­Hl4h€7/‘pjn6Pf TXçto’b—g'UCºZv éF?JаY:R$VDKAz3;W
fra: wIÔ+s1y₂kÊEQ!röMO0СG98.&)x,â52aNeÂuiL «dcô–à(SBmq%áï"-êûÉÀlHh4​7/‘‽îpjn6Pf T» Xçto’bg'UCèZvœ éFë?JùY:R$VDÇKAz3…;W