defaults:
  - model: seq2seq
  - vocab: vocab
  - data: data

seed: 42
device: cpu
n_epoch: 1000
batch_size: 48
val_batch_size: 32

optim:
  args:
    lr: 0.0
    weight_decay: 0.1
  scheduler:
    max_lr: 0.01
    pct_start: 0.1

checkpoint: 'seq2seq.pt'